name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set execute permission for deploy.sh
      run: chmod +x /home/ubuntu/nginx-gitops/deploy.sh

    - name: Deploy application
      run: |
        cd /home/ubuntu/nginx-gitops
        git pull https://github.com/piyush-1414/nginx-gitops.git main
        ./deploy.sh
