name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy to VM
      run: |
        sshpass -p 'piyush@12345' ssh ubuntu@172.177.187.189 << EOF
        cd /root/nginx-gitops
        git pull origin main
        ./deploy.sh
        EOF
