name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy application
      run: |
        cd /home/ubuntu/nginx-gitops
        git pull origin main
        ./deploy.sh
